Fix 1st 5 Functional Tests
DigiByte-Core/digibyte pull request #183
Opened 2024-03-05 19:05 UTC by JaredTate

This PR fixes the first 5 functional tests. I am splitting this up so it does not get super unwieldy to review for fixing all the tests.  Many changes are changing `COINBASE_MATURITY_ORIGINAL` to `COINBASE_MATURITY_2` to match core protocol terminology.  

To test this do:

Compile:

```
  ./autogen.sh
  ./configure
  make -j 8
```
Run Functional Tests
```
test/functional/test_runner.py
```
Should get:

![Screenshot 2024-03-05 at 11 58 23 AM](https://github.com/DigiByte-Core/digibyte/assets/13957390/b5ef81e7-8c0e-4562-ac28-b49ef0f5752b)

2024-03-05 21:19 UTC, Jongjan88 requested changes
@JaredTate Thank you for the pr. Nice work.

2024-03-05 21:19 UTC, Jongjan88 commented on test/functional/wallet_backup.py
> +        # Sum = 82,080,000 DGB
Can we change:

`# Sum = 82,080,000 DGB`

To

```
# At this point, there are 214 blocks (103 for setup, then 10 rounds, then 101.)
# 114 are mature, so the sum of all wallets should be 114 * 72000 = 82,080,000.
```

2024-03-05 21:19 UTC, Jongjan88 commented on test/functional/rpc_fundrawtransaction.py
Is this change correct?

`oldBalance+Decimal('72000.19109500') `
**to** 
`oldBalance+Decimal('6335901.85210000') ?`

This file is not working. And the first 5 python tests don't need it. Maybe we should remove it from the pr?

2024-03-05 21:32 UTC, JaredTate commented on test/functional/rpc_fundrawtransaction.py
Just removed this one, thats where I was last stuck, the changes above that in fund raw transaction work and fix bugs.

2024-03-05 21:32 UTC, JaredTate commented on test/functional/wallet_backup.py
> +        # Sum = 82,080,000 DGB
Done, thanks for editing that.

2024-03-05 21:34 UTC, ghost approved these changes

2024-03-05 21:46 UTC, JaredTate commented
lol

2024-03-05 21:47 UTC, Jongjan88 commented
> lol

sorry!! I did gh pr close.

2024-03-05 21:50 UTC, JaredTate commented
> > lol
> 
> sorry!! I did gh pr close.

It's all good! Thanks for your help! :)

2024-03-05 22:06 UTC, gto90 approved these changes
utACK

Thank you @JaredTate

2024-03-05 22:37 UTC, ycagel approved these changes
cACK. Thanks for the efforts @JaredTate!

2024-03-05 22:37 UTC, merged

2024-03-06 00:44 UTC, beggsdl commented
Nice work @JaredTate.  I was glad to see you got rid of COINBASE_MATURITY_ORIGINAL and used COINBASE_MATURITY_2 instead.