Trivial: Updated outdated GitHub urls
DigiByte-Core/digibyte pull request #61
Opened 2021-07-27 02:57 UTC by gto90

Updated old GitHub repository URLs with the DigiByte-Core url.

2021-07-27 03:09 UTC, ChillingSilence requested changes
There's a bunch that have been changed to digibyte-core/digibyte which should be bitcoin/bitcoin and a few things that are just not relevant to us at all which we should just nuke.

2021-07-27 03:09 UTC, ChillingSilence commented on contrib/debian/changelog
> +  * Revert to Qt4, due to https://github.com/DigiByte-Core/digibyte/issues/9038
Some such as this are broken still, as these should be github.com/bitcoin/bitcoin/issues/9038

2021-07-27 03:09 UTC, ChillingSilence commented on contrib/gitian-descriptors/gitian-win.yml
> +  # heap, causing non-determinism. See discussion in https://github.com/DigiByte-Core/digibyte/pull/6900
Another one for bitcoin repos

2021-07-27 03:09 UTC, ChillingSilence commented on contrib/rpm/README.md
> +[DigiByte git repository](https://github.com/DigiByte-Core/digibyte) but are not part of
Should probs even just look at removing this file / directory, given we don't maintain any rpms and this is out of date

2021-07-27 03:09 UTC, ChillingSilence commented on depends/README.md
> +RISC-V known issue: gcc-7.3.0 and gcc-7.3.1 result in a broken `test_digibyte` executable (see https://github.com/DigiByte-Core/digibyte/pull/13543),
For bitcoin/bitcoin

2021-07-27 03:09 UTC, ChillingSilence commented on doc/REST-interface.md
> +https://github.com/DigiByte-Core/bips/blob/master/bip-0064.mediawiki
Also for bitcoin/bitcoin

2021-07-27 03:17 UTC, gto90 commented
Good catch @ChillingSilence , I'll work through those and update accordingly.

2021-07-27 03:44 UTC, ChillingSilence commented
Good stuff mate , and ty for getting these fixed 👍

2021-08-08 23:52 UTC, gto90 commented
I am going to close this and reopen it against the feature branch.

2021-08-08 23:52 UTC, closed without merging